#
#  GitLab CI/CD configuration
#
#  Copyright (C)
#  Honda Research Institute Europe GmbH
#  Carl-Legien-Str. 30
#  63073 Offenbach/Main
#  Germany
#
#  UNPUBLISHED PROPRIETARY MATERIAL.
#  ALL RIGHTS RESERVED.
#
#


default:
    image: dmz-gitlab.honda-ri.de:5050/gitlabrunner/buildcontainers/hri-eu-main:latest
    interruptible: true

stages:
    - test
    - check

variables:
    TBCORE_VERSION: "4.2"

test:
    timeout: 20 minutes
    stage: test
    script:
        - ./ci-test.sh $TBCORE_VERSION

#check:
#    stage: check
#    script:
#        - ./ci-check.sh $TBCORE_VERSION
#    allow_failure: true


sonarqube:
  stage: check
  script:
    - ./ci-sonarqube.sh $TBCORE_VERSION
  needs: []

# EOF
